const { GoogleGenerativeAI } = require("@google/generative-ai");

// Fetch the API key from environment variables
const apiKey = process.env.GEMINI_API_KEY;
let genAI = null;
if (apiKey) {
    genAI = new GoogleGenerativeAI(apiKey);
}

// Fallback mock responses if no API key is provided
const getMockExplanation = (code, language) => {
    return `### Code Explanation (Mock Mode - Add GEMINI_API_KEY to your .env to connect to Gemini)

Here is a brief mock explanation of your code:
1. Your code appears to be written in **${language}**.
2. It contains code structure that AI can analyze for logic flow.
3. Once you set a valid \`GEMINI_API_KEY\` in your server's \`.env\`, this section will display detailed, real-time line-by-line explanations generated by Gemini!`;
};

const getMockReview = (code, language) => {
    return `### Code Review & Recommendations (Mock Mode - Add GEMINI_API_KEY to your .env to connect to Gemini)

1. **Optimize Structure**: Consider refactoring helper functions for readability.
2. **Key Missing**: Set up your \`GEMINI_API_KEY\` to perform standard bug checks, memory leak detection, and security reviews.
3. **Language**: Validated language structure as **${language}**.`;
};

const getMockAutocomplete = (textBeforeCursor, textAfterCursor) => {
    // If the text ends with a common open bracket, suggest some simple completion
    const trimmed = textBeforeCursor.trim();
    if (trimmed.endsWith("{")) {
        return "\n    // Code here\n}";
    }
    if (trimmed.endsWith("std::cout <<")) {
        return " \"Hello, World!\" << std::endl;";
    }
    return "";
};

// Explain Code
const explainCode = async (req, res) => {
    try {
        const { code, language } = req.body;
        if (!code) {
            return res.status(400).json({ message: "No code provided" });
        }

        if (!genAI) {
            return res.json({ explanation: getMockExplanation(code, language || "cpp") });
        }

        const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
        const prompt = `You are an expert software developer. Explain the following ${language || "cpp"} code clearly and concisely. Break it down step-by-step and keep it formatting-friendly with markdown:
\`\`\`${language || "cpp"}
${code}
\`\`\``;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        return res.json({ explanation: response.text() });
    } catch (error) {
        console.error("Gemini Explain Error:", error);
        // Serve mock explanation as fallback with warning
        const fallbackText = `### AI Rate Limit / API Error (Temporary Fallback)

Google Gemini API encountered an error (e.g. rate limit, quota exceeded, or network issue). Please try again shortly.

Meanwhile, here is a general analysis of your code:
- **Language**: ${req.body.language || "cpp"}
- **Analysis**: The code has been received by the workspace server but cannot be analyzed by Gemini right now. Please review syntax structure locally.`;
        return res.json({ explanation: fallbackText });
    }
};

// Review Code
const reviewCode = async (req, res) => {
    try {
        const { code, language } = req.body;
        if (!code) {
            return res.status(400).json({ message: "No code provided" });
        }

        if (!genAI) {
            return res.json({ review: getMockReview(code, language || "cpp") });
        }

        const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
        const prompt = `You are an expert code reviewer. Perform a code review of the following ${language || "cpp"} code. Identify potential bugs, optimization opportunities, clean code violations, and security flaws. Provide constructive feedback and refactoring examples using markdown:
\`\`\`${language || "cpp"}
${code}
\`\`\``;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        return res.json({ review: response.text() });
    } catch (error) {
        console.error("Gemini Review Error:", error);
        // Serve mock review as fallback with warning
        const fallbackText = `### AI Rate Limit / API Error (Temporary Fallback)

Google Gemini API encountered an error (e.g. rate limit, quota exceeded, or network issue). Please try again shortly.

Meanwhile, here are some general code recommendations:
1. **Formatting**: Ensure consistent indentation and clean brace placement.
2. **Review**: Bug check, logic trace, and dependency verification should be performed manually until API quota resets.`;
        return res.json({ review: fallbackText });
    }
};

// Autocomplete Code
const autocompleteCode = async (req, res) => {
    const { textBeforeCursor, textAfterCursor } = req.body;
    try {
        if (!textBeforeCursor && textBeforeCursor !== "") {
            return res.status(400).json({ message: "No context provided" });
        }

        if (!genAI) {
            return res.json({ suggestion: getMockAutocomplete(textBeforeCursor, textAfterCursor) });
        }

        const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
        
        // Construct prompt for autocomplete
        const prompt = `You are a code completion engine. Your job is to autocomplete the next few characters or lines starting exactly from the end of the input code.
Do NOT repeat the code already provided.
Do NOT wrap the completion in markdown formatting or code blocks.
Do NOT write explanations or chat responses.
Return ONLY the characters or lines that should immediately follow the input code to complete it logically.

Input code:
${textBeforeCursor}

Complete the code starting exactly from where the input code left off:`;

        const result = await model.generateContent({
            contents: [{ role: 'user', parts: [{ text: prompt }] }],
            generationConfig: {
                maxOutputTokens: 60,
                temperature: 0.1, // Low temperature for deterministic completions
            }
        });
        
        const response = await result.response;
        let suggestion = response.text();
        
        // Clean up markdown block quotes if Gemini accidentally returned them
        if (suggestion.startsWith("```")) {
            suggestion = suggestion.replace(/^```[a-zA-Z0-9-]*\n/, "").replace(/\n```$/, "");
        }
        
        return res.json({ suggestion });
    } catch (error) {
        console.error("Gemini Autocomplete Error:", error);
        // Serve mock autocomplete silently
        return res.json({ suggestion: getMockAutocomplete(textBeforeCursor, textAfterCursor) });
    }
};

module.exports = {
    explainCode,
    reviewCode,
    autocompleteCode
};
